<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue'
import { Badge,Button,Card,CardContent,Dialog,DialogContent,DialogFooter,DialogHeader,DialogTitle,Input,Switch,Table,TableBody,TableCell,TableEmpty,TableHead,TableHeader,TableRow } from '@tabtab/ui'
import { Pencil,Plus,Search,Trash2 } from 'lucide-vue-next'
import { systemApi,type Permission,type Role } from '@/api/client'
const rows=ref<Role[]>([]),permissions=ref<Permission[]>([]),keyword=ref(''),open=ref(false),editing=ref<string|null>(null),error=ref('')
const form=reactive({code:'',name:'',description:'',isEnabled:true,permissions:[] as string[]})
const filtered=computed(()=>rows.value.filter(x=>!keyword.value||`${x.name}${x.code}`.toLowerCase().includes(keyword.value.toLowerCase())))
const groups=computed(()=>Object.groupBy(permissions.value,x=>x.group))
async function load(){try{[rows.value,permissions.value]=await Promise.all([systemApi.roles(),systemApi.permissions()])}catch(e){error.value=e instanceof Error?e.message:'加载失败'}}
function show(row?:Role){editing.value=row?.id??null;Object.assign(form,row?{code:row.code,name:row.name,description:row.description??'',isEnabled:row.isEnabled,permissions:[...row.permissions]}:{code:'',name:'',description:'',isEnabled:true,permissions:[]});open.value=true}
async function save(){try{editing.value?await systemApi.updateRole(editing.value,form):await systemApi.createRole(form);open.value=false;await load()}catch(e){error.value=e instanceof Error?e.message:'保存失败'}}
async function remove(row:Role){if(!confirm(`确定删除角色 ${row.name}？`))return;try{await systemApi.deleteRole(row.id);await load()}catch(e){error.value=e instanceof Error?e.message:'删除失败'}}
onMounted(load)
</script>
<template><div class="space-y-5"><div class="flex items-center justify-between"><div><h1 class="text-3xl font-bold">角色管理</h1><p class="text-muted-foreground">维护角色、状态及权限集合</p></div><Button @click="show()"><Plus class="mr-2 h-4 w-4"/>新增角色</Button></div><Card><CardContent class="flex gap-2 pt-6"><Input v-model="keyword" class="max-w-sm" placeholder="角色名称或编码"/><Button><Search class="mr-2 h-4 w-4"/>查询</Button></CardContent></Card><p v-if="error" class="text-sm text-destructive">{{error}}</p><Card><CardContent class="p-0"><Table><TableHeader><TableRow><TableHead>角色</TableHead><TableHead>编码</TableHead><TableHead>权限</TableHead><TableHead>状态</TableHead><TableHead class="text-right">操作</TableHead></TableRow></TableHeader><TableBody><TableRow v-for="row in filtered" :key="row.id"><TableCell><div class="font-medium">{{row.name}}</div><div class="text-xs text-muted-foreground">{{row.description||'-'}}</div></TableCell><TableCell class="font-mono">{{row.code}}</TableCell><TableCell><Badge variant="secondary">{{row.permissions.length}} 项</Badge></TableCell><TableCell><Badge :variant="row.isEnabled?'default':'outline'">{{row.isEnabled?'启用':'停用'}}</Badge></TableCell><TableCell class="text-right"><Button size="icon" variant="ghost" @click="show(row)"><Pencil class="h-4 w-4"/></Button><Button size="icon" variant="ghost" :disabled="row.isSystem" @click="remove(row)"><Trash2 class="h-4 w-4"/></Button></TableCell></TableRow><TableEmpty v-if="!filtered.length" :colspan="5">暂无角色</TableEmpty></TableBody></Table></CardContent></Card><Dialog v-model:open="open"><DialogContent class="max-w-2xl"><DialogHeader><DialogTitle>{{editing?'编辑':'新增'}}角色</DialogTitle></DialogHeader><form class="space-y-4" @submit.prevent="save"><div class="grid gap-3 sm:grid-cols-2"><Input v-model="form.code" required :disabled="!!editing" placeholder="角色编码"/><Input v-model="form.name" required placeholder="角色名称"/><Input v-model="form.description" class="sm:col-span-2" placeholder="角色说明"/></div><div class="flex items-center justify-between rounded-md border p-3"><span>启用角色</span><Switch v-model="form.isEnabled"/></div><div class="max-h-72 space-y-4 overflow-auto rounded-md border p-4"><div v-for="(items,name) in groups" :key="name"><p class="mb-2 font-medium">{{name}}</p><div class="grid gap-2 sm:grid-cols-2"><label v-for="item in items" :key="item.id" class="flex gap-2 text-sm"><input v-model="form.permissions" type="checkbox" :value="item.code"/>{{item.name}} <span class="text-muted-foreground">{{item.code}}</span></label></div></div></div><DialogFooter><Button type="button" variant="outline" @click="open=false">取消</Button><Button type="submit">保存</Button></DialogFooter></form></DialogContent></Dialog></div></template>
