<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue'
import { Button,Input } from '@tabtab/ui'
import { Pencil,Plus,Trash2,X } from 'lucide-vue-next'
import { systemApi,type Department } from '@/api/client'
type FlatDepartment=Department&{level:number}
const rows=ref<Department[]>([]),showForm=ref(false),editingId=ref<string|null>(null),error=ref('')
const form=reactive({parentId:null as string|null,code:'',name:'',sort:0,isEnabled:true})
const flat=computed(()=>{const result:FlatDepartment[]=[];const visit=(items:Department[],level=0)=>items.forEach(x=>{result.push({...x,level});visit(x.children,level+1)});visit(rows.value);return result})
const msg=(e:unknown,f:string)=>e instanceof Error?e.message:f
async function load(){error.value='';try{rows.value=await systemApi.departments()}catch(e){error.value=msg(e,'加载失败')}}
function open(row?:Department){editingId.value=row?.id??null;Object.assign(form,row?{parentId:row.parentId??null,code:row.code,name:row.name,sort:row.sort,isEnabled:row.isEnabled}:{parentId:null,code:'',name:'',sort:0,isEnabled:true});showForm.value=true}
async function save(){try{editingId.value?await systemApi.updateDepartment(editingId.value,form):await systemApi.createDepartment(form);showForm.value=false;await load()}catch(e){error.value=msg(e,'保存失败')}}
async function remove(row:Department){if(!confirm(`确定删除机构 ${row.name}？`))return;try{await systemApi.deleteDepartment(row.id);await load()}catch(e){error.value=msg(e,'删除失败')}}
onMounted(load)
</script>
<template><div class="space-y-5"><div class="flex items-center justify-between"><div><h1 class="text-3xl font-bold">组织机构管理</h1><p class="text-muted-foreground">维护公司、部门层级及用户归属</p></div><Button @click="open()"><Plus class="mr-2 h-4 w-4"/>新增机构</Button></div><p v-if="error" class="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{{error}}</p><div class="overflow-x-auto rounded-lg border"><table class="w-full text-sm"><thead class="bg-muted/50"><tr><th class="p-3 text-left">机构名称</th><th class="p-3 text-left">机构编码</th><th class="p-3">用户数</th><th class="p-3">排序</th><th class="p-3">状态</th><th class="p-3 text-right">操作</th></tr></thead><tbody><tr v-for="row in flat" :key="row.id" class="border-t"><td class="p-3 font-medium" :style="{paddingLeft:`${12+row.level*24}px`}">{{row.level?'└ ':''}}{{row.name}}</td><td class="p-3 font-mono">{{row.code}}</td><td class="p-3 text-center">{{row.userCount}}</td><td class="p-3 text-center">{{row.sort}}</td><td class="p-3 text-center">{{row.isEnabled?'启用':'停用'}}</td><td class="p-3 text-right"><Button size="icon" variant="ghost" @click="open(row)"><Pencil class="h-4 w-4"/></Button><Button size="icon" variant="ghost" @click="remove(row)"><Trash2 class="h-4 w-4"/></Button></td></tr></tbody></table></div><div v-if="showForm" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form class="w-full max-w-md space-y-4 rounded-xl bg-background p-6" @submit.prevent="save"><div class="flex justify-between"><h2 class="text-xl font-semibold">{{editingId?'编辑':'新增'}}机构</h2><Button type="button" size="icon" variant="ghost" @click="showForm=false"><X class="h-4 w-4"/></Button></div><select v-model="form.parentId" class="h-10 w-full rounded-md border bg-background px-3"><option :value="null">顶级机构</option><option v-for="item in flat.filter(x=>x.id!==editingId)" :key="item.id" :value="item.id">{{'　'.repeat(item.level)}}{{item.name}}</option></select><Input v-model="form.code" required placeholder="机构编码"/><Input v-model="form.name" required placeholder="机构名称"/><Input v-model.number="form.sort" type="number" placeholder="排序"/><label class="text-sm"><input v-model="form.isEnabled" type="checkbox" class="mr-2"/>启用</label><div class="flex justify-end gap-2"><Button type="button" variant="outline" @click="showForm=false">取消</Button><Button type="submit">保存</Button></div></form></div></div></template>
