<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue'
import { Button,Input } from '@tabtab/ui'
import { Pencil,Plus,Trash2,X } from 'lucide-vue-next'
import { systemApi,type Menu } from '@/api/client'
type FlatMenu=Menu&{level:number}
const rows=ref<Menu[]>([]),showForm=ref(false),editingId=ref<string|null>(null),error=ref('')
const form=reactive({parentId:null as string|null,name:'',path:'',component:'',icon:'',permissionCode:'',sort:0,type:'Page',hidden:false,isEnabled:true})
const flat=computed(()=>{const result:FlatMenu[]=[];const visit=(items:Menu[],level=0)=>items.forEach(x=>{result.push({...x,level});visit(x.children,level+1)});visit(rows.value);return result})
async function load(){error.value='';try{rows.value=await systemApi.menus()}catch(e){error.value=message(e,'加载失败')}}
function open(row?:Menu){editingId.value=row?.id??null;Object.assign(form,row?{parentId:row.parentId??null,name:row.name,path:row.path,component:row.component??'',icon:row.icon??'',permissionCode:row.permissionCode??'',sort:row.sort,type:row.type,hidden:row.hidden,isEnabled:row.isEnabled}:{parentId:null,name:'',path:'',component:'',icon:'',permissionCode:'',sort:0,type:'Page',hidden:false,isEnabled:true});showForm.value=true}
async function save(){try{editingId.value?await systemApi.updateMenu(editingId.value,form):await systemApi.createMenu(form);showForm.value=false;await load()}catch(e){error.value=message(e,'保存失败')}}
async function remove(row:Menu){if(!confirm(`确定删除菜单 ${row.name}？`))return;try{await systemApi.deleteMenu(row.id);await load()}catch(e){error.value=message(e,'删除失败')}}
const message=(e:unknown,fallback:string)=>e instanceof Error?e.message:fallback
onMounted(load)
</script>
<template><div class="space-y-5"><div class="flex items-center justify-between"><div><h1 class="text-3xl font-bold">菜单管理</h1><p class="text-muted-foreground">维护导航层级、路由组件与权限标识</p></div><Button @click="open()"><Plus class="mr-2 h-4 w-4"/>新增菜单</Button></div><p v-if="error" class="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{{error}}</p><div class="overflow-x-auto rounded-lg border"><table class="w-full text-sm"><thead class="bg-muted/50"><tr><th class="p-3 text-left">菜单名称</th><th class="p-3 text-left">路由</th><th class="p-3 text-left">类型</th><th class="p-3 text-left">权限标识</th><th class="p-3">排序</th><th class="p-3">状态</th><th class="p-3 text-right">操作</th></tr></thead><tbody><tr v-for="row in flat" :key="row.id" class="border-t"><td class="p-3 font-medium" :style="{paddingLeft:`${12+row.level*24}px`}">{{row.level?'└ ':''}}{{row.name}}</td><td class="p-3 font-mono text-xs">{{row.path}}</td><td class="p-3">{{row.type}}</td><td class="p-3 font-mono text-xs">{{row.permissionCode||'-'}}</td><td class="p-3 text-center">{{row.sort}}</td><td class="p-3 text-center">{{row.isEnabled?'启用':'停用'}}</td><td class="p-3 text-right"><Button size="icon" variant="ghost" @click="open(row)"><Pencil class="h-4 w-4"/></Button><Button size="icon" variant="ghost" @click="remove(row)"><Trash2 class="h-4 w-4"/></Button></td></tr></tbody></table></div><div v-if="showForm" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form class="w-full max-w-xl space-y-4 rounded-xl bg-background p-6" @submit.prevent="save"><div class="flex justify-between"><h2 class="text-xl font-semibold">{{editingId?'编辑':'新增'}}菜单</h2><Button type="button" size="icon" variant="ghost" @click="showForm=false"><X class="h-4 w-4"/></Button></div><div class="grid gap-3 sm:grid-cols-2"><select v-model="form.parentId" class="h-10 rounded-md border bg-background px-3"><option :value="null">顶级菜单</option><option v-for="item in flat.filter(x=>x.id!==editingId)" :key="item.id" :value="item.id">{{'　'.repeat(item.level)}}{{item.name}}</option></select><select v-model="form.type" class="h-10 rounded-md border bg-background px-3"><option value="Directory">目录</option><option value="Page">页面</option><option value="ExternalLink">外链</option></select><Input v-model="form.name" required placeholder="菜单名称"/><Input v-model="form.path" required placeholder="路由地址"/><Input v-model="form.component" placeholder="组件标识"/><Input v-model="form.icon" placeholder="图标名称"/><Input v-model="form.permissionCode" placeholder="权限标识"/><Input v-model.number="form.sort" type="number" placeholder="排序"/></div><div class="flex gap-6 text-sm"><label><input v-model="form.isEnabled" type="checkbox" class="mr-2"/>启用</label><label><input v-model="form.hidden" type="checkbox" class="mr-2"/>隐藏</label></div><div class="flex justify-end gap-2"><Button type="button" variant="outline" @click="showForm=false">取消</Button><Button type="submit">保存</Button></div></form></div></div></template>
