<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../MyBaseSystem.Application/MyBaseSystem.Application.csproj" />
    <ProjectReference Include="../MyBaseSystem.Infrastructure/MyBaseSystem.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
</Project>
