<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Button, Input } from '@tabtab/ui'
import { Plus, Trash2, X } from 'lucide-vue-next'
import { systemApi, type Role } from '@/api/client'
const rows=ref<Role[]>([]);const showForm=ref(false);const error=ref('');const form=reactive({code:'',name:'',description:'',isEnabled:true,permissions:[] as string[]})
async function load(){try{rows.value=await systemApi.roles()}catch(e){error.value=e instanceof Error?e.message:'加载失败'}}
async function create(){try{await systemApi.createRole(form);showForm.value=false;Object.assign(form,{code:'',name:'',description:'',isEnabled:true,permissions:[]});await load()}catch(e){error.value=e instanceof Error?e.message:'创建失败'}}
async function remove(row:Role){if(!confirm(`确定删除角色 ${row.name}？`))return;try{await systemApi.deleteRole(row.id);await load()}catch(e){error.value=e instanceof Error?e.message:'删除失败'}}
onMounted(load)
</script>
<template><div class="space-y-5"><div class="flex items-center justify-between"><div><h1 class="text-3xl font-bold">角色管理</h1><p class="text-muted-foreground">角色与权限集合维护</p></div><Button @click="showForm=true"><Plus class="mr-2 h-4 w-4"/>新增角色</Button></div><p v-if="error" class="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{{ error }}</p><div class="overflow-x-auto rounded-lg border"><table class="w-full text-sm"><thead class="bg-muted/50"><tr><th class="p-3 text-left">名称</th><th class="p-3 text-left">编码</th><th class="p-3 text-left">权限数</th><th class="p-3">状态</th><th class="p-3 text-right">操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id" class="border-t"><td class="p-3"><div class="font-medium">{{row.name}}</div><div class="text-muted-foreground">{{row.description}}</div></td><td class="p-3 font-mono">{{row.code}}</td><td class="p-3">{{row.permissions.length}}</td><td class="p-3 text-center">{{row.isEnabled?'启用':'停用'}}</td><td class="p-3 text-right"><Button size="icon" variant="ghost" :disabled="row.isSystem" @click="remove(row)"><Trash2 class="h-4 w-4"/></Button></td></tr></tbody></table></div><div v-if="showForm" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form class="w-full max-w-md space-y-4 rounded-xl bg-background p-6" @submit.prevent="create"><div class="flex justify-between"><h2 class="text-xl font-semibold">新增角色</h2><Button type="button" size="icon" variant="ghost" @click="showForm=false"><X class="h-4 w-4"/></Button></div><Input v-model="form.code" required placeholder="角色编码，如 operator"/><Input v-model="form.name" required placeholder="角色名称"/><Input v-model="form.description" placeholder="描述"/><div class="flex justify-end gap-2"><Button type="button" variant="outline" @click="showForm=false">取消</Button><Button type="submit">保存</Button></div></form></div></div></template>
